### ISSUE TITLE
[Feature Request] Dropdown component

### ISSUE THREAD

**Issue by ultralabed** [trendmicro-frontend/tonic-ui#177]
We really need this!!!!

**Comment by joyfulelement** [comment]
Currently both Cloud One Common Frontend and Container Security Frontend are waiting on the availability of this component.

It is on their critical path to roll out the next UI release, please consider making this as a high priority feature request.

Thank you.

**Comment by roth1002** [comment]
WIP by @austinhung81

**Comment by cheton** [comment]
@ultralabed @joyfulelement 

Added in https://github.com/trendmicro-frontend/styled-ui/commit/ff5ab2edbc2f45f5dce68f8476893c1423083ea6

https://trendmicro-frontend.github.io/styled-ui/menu

It's planned to be released in v0.4.0
