### ISSUE TITLE
MDXComponent table layout

### ISSUE THREAD

**Issue by roth1002** [trendmicro-frontend/tonic-ui#19]
現在 document在呈現 props table的時候 相當不容易閱讀

![螢幕快照 2020-02-05 下午3 47 43](https://user-images.githubusercontent.com/8485590/73821452-f7203500-482e-11ea-8f7b-e12be35e3cb7.png)

**Comment by cheton** [comment]
Use GitHub Markdown style to implement table layout (https://github.com/cheton/styled-ui/commit/259b9cce8f34be3c32ecc2ea3432663c8fb95ea9)

**Comment by cheton** [comment]
Table view in a markdown document will look like so:

![image](https://user-images.githubusercontent.com/447801/73997830-a4638c00-499a-11ea-82d3-4151d0d9c1c9.png)
