### ISSUE TITLE
The pseudo class ":first-child" is potentially unsafe.

### ISSUE THREAD

**Issue by JimLin94** [trendmicro-frontend/tonic-ui#252]
Hi there,

Me and C1 folks got this warning from the console when some of the components are mounted. That would be lovely if it could be fixed sometime soon.

**The pseudo class ":first-child" is potentially unsafe when doing server-side rendering. Try changing it to ":first-of-type".**

![image](https://user-images.githubusercontent.com/7638055/98189035-1b8c7780-1f4f-11eb-9acb-f71c97938545.png)

![warn mov](https://user-images.githubusercontent.com/7638055/98189330-b2593400-1f4f-11eb-9be4-54a3477f285f.gif)

**Comment by JimLin94** [comment]
Duplicate #158

**Comment by cheton** [comment]
@JimLin94 

It will be fixed in https://github.com/trendmicro-frontend/styled-ui/pull/253
