### ISSUE TITLE
[Dark Mode] Git Page layout color issue

### ISSUE THREAD

**Issue by roth1002** [trendmicro-frontend/tonic-ui#30]
清Cache or 無痕模式會有

Firefox 一樣

<img width="974" alt="螢幕快照 2020-02-08 下午11 15 07" src="https://user-images.githubusercontent.com/8485590/74087614-fc98ac00-4ac8-11ea-8d1c-b2a360b3bf47.png">

**Comment by cheton** [comment]
Fixed in PR #27 with commit https://github.com/trendmicro-frontend/styled-ui/pull/27/files#diff-7b9a290e2714abbba72c0d5fe04f03b6 by removing `height="100%"` from `Main`.
