### ISSUE TITLE
Documentation for Stack component has `unexpected token` error

### ISSUE THREAD

**Issue by gsaran** [trendmicro-frontend/tonic-ui#308]
Stack component's examples on Styled UI Docs site are showing an `unexpected token error` as shown in attached screenshot. 

![image](https://user-images.githubusercontent.com/18233426/117714195-95264c00-b1a4-11eb-9446-4657dda02d43.png)

**Reason**: Editable example code editor doesn't support `optional chaining` operator and is causing this error. Removing `?.` from examples fix the issue.

**Comment by cheton** [comment]
Thank you for the feedback. It's fixed in the docs.
