### ISSUE TITLE
[Feature Request] Add customized tooltips

### ISSUE THREAD

**Issue by zihengCat** [trendmicro-frontend/tonic-ui#310]
Hi, could we enhance `Tooltip` component let it be able to consume and render a `React.ReactNode`?
The effect just like Material-UI customized tooltip shows below. 
![Screen Shot 2021-05-13 at 14 57 49](https://user-images.githubusercontent.com/19472493/118091258-2b54af00-b3fd-11eb-9fcb-5049dfa501e5.png)

**Comment by cheton** [comment]
@zihengCat

You can customize tooltip as below:

![image](https://user-images.githubusercontent.com/447801/120600934-e829b100-c47b-11eb-97ef-84618a924eb0.png)

**Comment by zihengCat** [comment]
@cheton
Wow, fantastic! 
Let it be documented. A helpful tooltip example.

**Comment by zihengCat** [comment]
@cheton 
Tooltip's `label` property could be `ReactNode` type!
![Screen Shot 2021-06-03 at 17 10 59](https://user-images.githubusercontent.com/19472493/120619759-e1586980-c48e-11eb-9cae-ad2e1779b1ec.png)

**Comment by cheton** [comment]
It's a kind of mistake in the API document. I will create a PR to fix incorrect value in docs. Thank you.

**Comment by zihengCat** [comment]
@cheton 
And would you like add a customized HTML `Tooltip` example to Tonic Styled UI demo page? It's so cool!

**Comment by cheton** [comment]
@zihengCat 

![image](https://user-images.githubusercontent.com/447801/120627278-15835880-c496-11eb-9aef-70eb00a1af86.png)

Added in PR #316
