### ISSUE TITLE
Popover position for menu item will alwasy have a 32px gap

### ISSUE THREAD

**Issue by TrendAlan** [trendmicro-frontend/tonic-ui#332]
Since the MenuList use transform style such as "transform: translate(0px, 32px);" to make it under or on the top of the menu button, if I use popover for a menu item as below:

```
	<Popover trigger="hover" nextToCursor>
		<PopoverTrigger>
			<Box>
				<MenuItem onKeyDown={(e) =>handleClick(e)} >
					<Text className="menu-item" ref={ref}>{item.name}</Text>
				</MenuItem>
			</Box>
		</PopoverTrigger>
		<PopoverContent>
			<PopoverBody>
				<Text>{item.name}</Text>
			</PopoverBody>
		</PopoverContent>
	</Popover>
```
The popover position will always have a 32px gap between the Text element.
But if change the transform style for MenuList to margin-top:32px, the position for popover will be correct.

**Comment by cheton** [comment]
Hi @TrendAlan 
I will close this issue when PR #297 is merged. You can use `MenuTrigger` to render anything you want.
