### ISSUE TITLE
Hope Drawer can support disabling portal

### ISSUE THREAD

**Issue by KKzLEO** [trendmicro-frontend/tonic-ui#333]
Hi, thanks for creating this awesome library, I am having fun to use it, but I am wondering if you can support disabling drawer component's `portal` behavior? Because if you want to make a drawer clipped under the app bar or persistent(to push content away when opening drawer), you need to put the dom of drawer directly under the parent div instead of portal. 

Drawer clipped under the app bar example: https://material-ui.com/components/drawers/#clipped-under-the-app-bar
Persistent drawer example: https://material-ui.com/components/drawers/#clipped-under-the-app-bar

**Comment by KKzLEO** [comment]
If you don't mind, I can create a PR to adjust it

**Comment by cheton** [comment]
@KKzLEO Please create a PR so that we can know what can be improved. Thank you.

**Comment by cheton** [comment]
Hi @KKzLEO 

According to your needs, you can simply use `DrawerContent`, `DrawerHeader`, `DrawerBody`, and `DrawerFooter` to render the layout without wrapping a `Drawer` on top of it, like so:

```jsx
<DrawerContent
  position="relative"
  height="100vh"
>
  <DrawerHeader>
    This is drawer header
  </DrawerHeader>
  <DrawerBody>
    This is drawer body
  </DrawerBody>
  <DrawerFooter>
    This is drawer footer
  </DrawerFooter>
</DrawerContent>
```

As so, you won't get trouble with the portal behavior.
