### ISSUE TITLE
MenuItem with disabled={false} not accessible with keyboard

### ISSUE THREAD

**Issue by gsaran** [trendmicro-frontend/tonic-ui#342]
Adding `disabled` prop value even if it's false for `MenuItem` component makes in inaccessible with keyboard. 

Steps to reproduce the issue are in attached video:
https://user-images.githubusercontent.com/18233426/131876098-4dab691e-5579-43e2-8353-e21472213235.mov

**Comment by cheton** [comment]
Hi @gsaran 

This's fixed in PR #384 and v0.21.1
