### ISSUE TITLE
MenuButton not accessible on Safari browser

### ISSUE THREAD

**Issue by gsaran** [trendmicro-frontend/tonic-ui#343]
`MenuButton` is not accessible on `Safari` browser with keyboard's Tab key. On `Chrome`, `Firefox` & `Edge`(on MacOS) it can be accessed.
Same issue exists with `Button` component

https://user-images.githubusercontent.com/18233426/131891074-5d609d00-43eb-423d-8177-0724dee8b36e.mov

https://user-images.githubusercontent.com/18233426/131891102-637565e9-8afe-491b-93ad-452da1b565ca.mov

**Comment by cheton** [comment]
Hi @gsaran 

https://corehelpcenter.bqe.com/hc/en-us/articles/115003481673-Tab-key-is-not-working-on-Mac-Safari

You can resolve this issue by taking these steps:

1. Open the Safari browser on your Mac.
2. Select Safari > Preferences > Advanced.
3. To make it easier to navigate links and form elements, check the option 'Press Tab to highlight each item on a webpage.'

![image](https://user-images.githubusercontent.com/447801/142992789-f424d5c0-3738-4d8d-ad36-c4a4c2cc47d1.png)
