### ISSUE TITLE
Checkbox action cause Drawer shift in scrollable drawer body

### ISSUE THREAD

**Issue by timtnleeProject** [trendmicro-frontend/tonic-ui#344]
Checkbox action cause Drawer shift in scrolled drawer body

### Demo
https://codesandbox.io/s/issue-react-styled-ui-checkbox-in-drawer-f8rp0?file=/src/Demo.js

### Steps

- click open drawer
- scroll down the drawer body
- check any checkbox
- result: drawer is shifted

![optimized](https://user-images.githubusercontent.com/33143314/131940985-4d0a81b9-e607-49a0-be6c-1c1590a4fecf.gif)

![issue2](https://user-images.githubusercontent.com/33143314/131940989-d5091a0a-344f-4d03-a4d2-9ec03cabb4cc.gif)

### update

This issue also cause in Modal Body

**Comment by cheton** [comment]
Merged to `v0` and `master` branches
