### ISSUE TITLE
How to change `max-width` in Popover component?

### ISSUE THREAD

**Issue by zihengCat** [trendmicro-frontend/tonic-ui#356]
I found a problem in `Popover` component: inner popover content has a `max-width` limitation at `288px`. I don't know how to change or disable it.

It seems the `max-width` limitation comes from original `popper.js` library, is their any ways to change it?

<img width="1440" alt="Screen Shot 2021-10-22 at 15 20 12" src="https://user-images.githubusercontent.com/19472493/138411084-f3c1a661-8236-43c3-8ca0-a2e92de99153.png">

**Comment by cheton** [comment]
Hi @zihengCat 

You can set the `maxWidth` prop on `PopoverContent` to change the maximum width of your popover content.

![image](https://user-images.githubusercontent.com/447801/139026640-b8211a5d-eb88-452d-9d19-09f3452dff9c.png)

**Comment by zihengCat** [comment]
@cheton Great, thank you for your help!
