### ISSUE TITLE
[ Demo Page ] - Code Block lose top border

### ISSUE THREAD

**Issue by roth1002** [trendmicro-frontend/tonic-ui#80]
![螢幕快照 2020-03-24 下午2 51 48](https://user-images.githubusercontent.com/8485590/77396677-1d019900-6ddf-11ea-9f52-3df2100c72a8.png)

**Comment by ultralabed** [comment]
Does this issue still exist?

**Comment by roth1002** [comment]
Yes

**Comment by austinhung81** [comment]
fixed in #195
